name: Deploy to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install Git LFS
        run: git lfs install

      - name: Push directly to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "samirxnr@gmail.com"
          git config --global user.name "Samirsonar"

          # Clone Hugging Face Space repo
          git clone https://Samirsonar:$HF_TOKEN@huggingface.co/spaces/samir118/ecommerce-dashboard hf

          # Copy project files into Hugging Face repo root
          rsync -av --exclude='.git' ./ hf/
          
          # Push to Hugging Face
          cd hf
          git add .
          git commit -m "Auto deploy from GitHub"
          git push https://Samirsonar:$HF_TOKEN@huggingface.co/spaces/samir118/ecommerce-dashboard
